source 'https://rubygems.org'
ruby '2.1.4'
gem 'better_errors'
gem 'binding_of_caller'
gem 'byebug'
gem 'capybara'
gem 'coffee-rails', '~> 4.1.0'
gem 'database_cleaner'
gem 'factory_girl_rails'
gem 'faker'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'launchy'
gem 'pg'
gem 'pry-rails'
gem 'pry-rescue'
gem 'quiet_assets'
gem 'rails', '4.2.0'
gem 'rails_layout'
gem 'redcarpet'
gem 'responders'
gem 'rest-client'
gem 'rspec_junit_formatter'
gem 'rspec-rails'
gem 'sass-rails', '~> 5.0'
gem 'selenium-webdriver'
gem 'slim-rails'
gem 'spring'
gem 'spring-commands-rspec'
gem 'sqlite3'
gem 'thin'
gem 'turbolinks'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'uglifier', '>= 1.3.0'
gem 'web-console', '~> 2.0'
gem 'webmock'
